general:
  cv: 6
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp
  overwrite_output_dir: False
  save_models: False
  show_plots: False
  metric: "balanced_accuracy_score"
  min_duration: "60 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  # - dt-finger_both
  # - dt-finger_ott
  - dt-finger_own
  # - dt-finger_tugraz
  - knn_dtw-oned
  - knn_dtw-twod
  # - knn_dtw-seqfinger_both
  # - knn_dtw-seqfinger_ott
  - knn_dtw-seqfinger_own
  # - knn_dtw-seqfinger_tugraz
  # - knn-finger_both
  # - knn-finger_ott
  - knn-finger_own
  # - knn-finger_tugraz
  # - mlp-finger_both
  # - mlp-finger_ott
  - mlp-finger_own
  # - mlp-finger_tugraz
  # - ott_algo-finger_ott
  # - svm_dtw-seqfinger_both
  # - svm_dtw-seqfinger_ott
  - svm_dtw-seqfinger_own
  # - svm_dtw-seqfinger_tugraz
  # - svm-finger_both
  # - svm-finger_ott
  - svm-finger_own
  # - svm-finger_tugraz

defaults:
  duration: &duration "30 seconds"
  step_duration: &step_duration "10 seconds"
  tsfresh_data: &tsfresh_data ./data/csv-files/prepared/dataset/train/tsfresh-features_0.5.0_minimal_60seconds.data
  normalize: &normalize True
  n_jobs: &n_jobs 3

models:
  knn_dtw-oned:
    frequency: "50ms"
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-twod:
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_ott:
    normalize: True
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_own:
    normalize: True
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_both:
    normalize: True
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_tsfresh:
    default_fc_parameters: MinimalFCParameters
    n_jobs: *n_jobs
    normalize: True
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_ott:
    duration: *duration
    normalize: False
    step_duration: *step_duration
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_own:
    duration: *duration
    normalize: False
    step_duration: *step_duration
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_tugraz:
    duration: *duration
    normalize: True
    step_duration: *step_duration
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_both:
    duration: *duration
    normalize: True
    step_duration: *step_duration
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_tsfresh:
    n_jobs: *n_jobs
    fdr_level: 0.23
    step_duration: *step_duration
    duration: *duration
    normalize: True
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      n_jobs: *n_jobs
      n_neighbors: 1

  ott_algo-finger_ott:
    normalize: False

  mlp-finger_ott:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_own:
    normalize: True
    classifier_hyperparameters:
      hidden_layer_sizes:
        - 3
      optimizer: "adam"
      batch_size: 6
      epochs: 123

  mlp-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_both:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 6
      optimizer: "adam"
      epochs: 123

  mlp-finger_tsfresh:
    normalize: *normalize
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 9
      optimizer: "adam"
      epochs: 123

  svm-finger_ott:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_own:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_both:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tsfresh:
    normalize: True
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_both:
    duration: *duration
    normalize: True
    step_duration: *step_duration

  svm_dtw-seqfinger_ott:
    duration: *duration
    normalize: True
    step_duration: *step_duration

  svm_dtw-seqfinger_own:
    duration: *duration
    normalize: True
    step_duration: *step_duration

  svm_dtw-seqfinger_tugraz:
    duration: *duration
    normalize: True
    step_duration: *step_duration

  dt-finger_ott:
    normalize: False

  dt-finger_own:
    normalize: False

  dt-finger_tugraz:
    normalize: False

  dt-finger_both:
    normalize: False

  dt-finger_tsfresh:
    normalize: True
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      min_samples_split: 5
