general:
  cv: 4
  data_dir: ./data/csv-files/prepared/dataset/train
  tsfresh_data: &tsfresh_data ./data/csv-files/prepared/dataset/train/minimal_extracted_tsfresh_features.data
  calc_cm: True
  output_dir: ./output/tmp
  overwrite_output_dir: False
  save_models: False
  show_plots: False
  metric: "balanced_accuracy_score"
  min_duration: "60 seconds"
  max_duration: "60 seconds"
  split: True

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - dt-finger_both
  - dt-finger_ott
  - dt-finger_own
  - dt-finger_tsfresh
  - dt-finger_tugraz
  - knn_dtw-oned
  - knn_dtw-twod
  - knn_dtw-seqfinger_both
  - knn_dtw-seqfinger_ott
  - knn_dtw-seqfinger_own
  # TODO - knn_dtw-seqfinger_tsfresh
  - knn_dtw-seqfinger_tugraz
  - knn-finger_both
  - knn-finger_ott
  - knn-finger_own
  - knn-finger_tsfresh
  - knn-finger_tugraz
  - mlp-finger_both
  - mlp-finger_ott
  - mlp-finger_own
  # - mlp-finger_tugraz
  # - ott_algo-finger_ott
  # - svm_dtw-seqfinger_both
  - svm_dtw-seqfinger_ott
  - svm_dtw-seqfinger_own
  # TODO - svm_dtw-seqfinger_tsfresh
  # - svm_dtw-seqfinger_tugraz
  - svm-finger_both
  # - svm-finger_ott
  - svm-finger_own
  - svm-finger_tsfresh
  # - svm-finger_tugraz
  - dt-finger_own

defaults:
  step_duration: &step_duration "10 seconds"

models:
  knn_dtw-oned:
    frequency: "5000ms"
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-twod:
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_ott:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_own:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_both:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_tsfresh:
    default_fc_parameters: MinimalFCParameters
    n_jobs: 3
    normalize: True
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_ott:
    duration: "30 seconds"
    normalize: False
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_own:
    duration: "30 seconds"
    normalize: False
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_tugraz:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_both:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    step_duration: *step_duration
    duration: "30 seconds"
    normalize: True
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      n_neighbors: 1

  ott_algo-finger_ott:
    normalize: False

  mlp-finger_ott:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_own:
    normalize: True
    classifier_hyperparameters:
      hidden_layer_sizes:
        - 3
      optimizer: "adam"
      batch_size: 6
      epochs: 123

  mlp-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_both:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 6
      optimizer: "adam"
      epochs: 123

  mlp-finger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 9
      optimizer: "adam"
      epochs: 123

  svm-finger_ott:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_own:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tugraz:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_both:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_both:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration

  svm_dtw-seqfinger_ott:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration

  svm_dtw-seqfinger_own:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration

  svm_dtw-seqfinger_tugraz:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration

  dt-finger_ott:
    normalize: False

  dt-finger_own:
    normalize: False

  dt-finger_tugraz:
    normalize: False

  dt-finger_both:
    normalize: False

  dt-finger_tsfresh:
    normalize: True
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
