general:
  cv: 3
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp
  overwrite_output_dir: False
  save_models: False
  show_plots: False
  metric: "balanced_accuracy_score"

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - dt-finger_both
  - dt-finger_ott
  - dt-finger_own
  - dt-finger_tsfresh
  - dt-finger_tugraz
  - knn_dtw-oned
  - knn_dtw-twod
  - knn_dtw-seqfinger_both
  - knn_dtw-seqfinger_ott
  - knn_dtw-seqfinger_own
  # TODO - knn_dtw-seqfinger_tsfresh
  - knn_dtw-seqfinger_tugraz
  - knn-finger_both
  - knn-finger_ott
  - knn_finger_own
  - knn-finger_tsfresh
  - knn-finger_tugraz
  - mlp-finger_both
  - mlp-finger_ott
  - mlp-finger_own
  # - mlp-finger_tugraz
  # - ott_algo-finger_ott
  # - svm_dtw-seqfinger_both
  - svm_dtw-seqfinger_ott
  - svm_dtw-seqfinger_own
  # TODO - svm_dtw-seqfinger_tsfresh
  # - svm_dtw-seqfinger_tugraz
  - svm-finger_both
  # - svm-finger_ott
  - svm-finger_own
  - svm-finger_tsfresh
  # - svm-finger_tugraz

models:
  knn_dtw-oned:
    frequency: "5000ms"
    multiple_of_min_len: 8
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-twod:
    multiple_of_min_len: 8
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_ott:
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_own:
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_tugraz:
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_both:
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_tsfresh:
    default_fc_parameters: MinimalFCParameters
    n_jobs: 3
    fdr_level: 0.23
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_ott:
    duration: "30 seconds"
    normalize: False
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_own:
    duration: "30 seconds"
    normalize: False
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_tugraz:
    duration: "30 seconds"
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_both:
    duration: "30 seconds"
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    duration: "30 seconds"
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  ott_algo-finger_ott: {}

  mlp-finger_ott:
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_own:
    classifier_hyperparameters:
      hidden_layer_sizes:
        - 3
      optimizer: "adam"
      batch_size: 6
      max_iter: 300
      max_fun:  20000
      epochs: 123


  mlp-finger_tugraz:
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_both:
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 6
      optimizer: "adam"
      epochs: 123

  mlp-finger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 9
      optimizer: "adam"
      epochs: 123

  svm-finger_ott:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_own:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tugraz:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_both:
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_both:
    duration: "30 seconds"
    normalize: True

  svm_dtw-seqfinger_ott:
    duration: "30 seconds"
    normalize: True

  svm_dtw-seqfinger_own:
    duration: "30 seconds"
    normalize: True

  svm_dtw-seqfinger_tugraz:
    duration: "30 seconds"
    normalize: True

  dt-finger_ott: {}

  dt-finger_own: {}

  dt-finger_tugraz: {}

  dt-finger_both: {}

  dt-finger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
