general:
  cv: "logo"
  # cv: 9
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp
  overwrite_output_dir: False
  save_models: False
  show_plots: False
  metric: "balanced_accuracy_score"
  min_duration: &min_duration "60 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True
  treat_negative_values: "absolute"
  write_cache: False
  # cache_path: ./output/cache.p

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating

models-to-run:
  - dt-finger_ott
  - dt-finger_own
  - dt-finger_tugraz
  - knn_dtw-oned
  - knn_dtw-seqfinger_ott
  - knn_dtw-seqfinger_seqown
  - knn_dtw-seqfinger_tugraz
  - knn-finger_ott
  - knn-finger_own
  - knn-finger_tugraz
  - mlp-finger_ott
  - mlp-finger_own
  - mlp-finger_tugraz
  - ott_algo-finger_ott
  - svm_dtw-seqfinger_ott
  - svm_dtw-seqfinger_seqown
  - svm_dtw-seqfinger_tugraz
  - svm-finger_ott
  - svm-finger_own
  - svm-finger_tugraz

defaults:
  duration: &duration "30 seconds"
  step_duration: &step_duration "10 seconds"
  tsfresh_data: &tsfresh_data ./data/csv-files/prepared/dataset/train/tsfresh-features_0.5.0_minimal_60seconds.data
  normalize: &normalize True
  n_jobs: &n_jobs 3
  stop_early: &stop_early True
  patience: &patience 11
  epochs: &epochs 250
  verbose: &verbose 1

models:
  knn_dtw-oned:
    normalize: *normalize
    data:
      fix_duration: *min_duration
      frequency: "20ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-twod:
    data:
      max_len: 100000
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_ott:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_own:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_tugraz:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_tsfresh:
    default_fc_parameters: MinimalFCParameters
    n_jobs: *n_jobs
    normalize: *normalize
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_ott:
    normalize: False
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    data:
      duration: *duration
      step_duration: *step_duration

  knn_dtw-seqfinger_seqown:
    normalize: False
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    data:
      duration: *duration
      step_duration: *step_duration

  knn_dtw-seqfinger_tugraz:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    data:
      duration: *duration
      step_duration: *step_duration

  ott_algo-finger_ott:
    normalize: False

  mlp-finger_ott:
    normalize: *normalize
    classifier:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  mlp-finger_own:
    normalize: *normalize
    classifier:
      hidden_layer_sizes:
        - 5
      dropout: 0.05
      optimizer: "adam"
      batch_size: 1
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  mlp-finger_tugraz:
    normalize: *normalize
    classifier:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  svm-finger_ott:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_own:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"
      class_weight: "balanced"

  svm-finger_tugraz:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_tsfresh:
    normalize: *normalize
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_ott:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  svm_dtw-seqfinger_seqown:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  svm_dtw-seqfinger_tugraz:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  dt-finger_ott:
    normalize: False

  dt-finger_own:
    normalize: *normalize
    classifier:
      min_samples_split: 10
      class_weight: "balanced"
      min_samples_leaf: 3

  dt-finger_tugraz:
    normalize: False

  dt-finger_tsfresh:
    normalize: *normalize
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier:
      min_samples_split: 5
