general:
  balance: True
  balance_polarity: True
  normalize_fingerprints: False
  calc_train_score: True
  verbose: False
  n_jobs: 3
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp
  overwrite_output_dir: False
  save_models: False
  show_plots: False
  min_duration: &min_duration "60 seconds"
  step_duration: "30 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True
  min_len: 0
  max_len: null
  repeat: null
  treat_negative_values: "absolute"
  cache_dir: ./cache

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - lgbm-finger_ott
  - lgbm-finger_own
  - lgbm-finger_relown
  - lgbm-finger_tugraz
  - lgbm-finger_all
  - knn-finger_ott
  - knn-finger_own
  - knn-finger_tugraz
  - mlp-finger_ott
  - mlp-finger_own
  - mlp-finger_tugraz
  - mlp-finger_relown
  - mlp-finger_all
  - rf-finger_ott
  - rf-finger_own
  - rf-finger_relown
  - rf-finger_tugraz
  - rf-finger_all
  - svm-finger_ott
  - svm-finger_own
  - svm-finger_tugraz

defaults:
  duration: &duration "30 seconds"
  step_duration: &step_duration "10 seconds"
  optimizer: &optimizer "adam"
  dropout: &dropout 0.01
  n_jobs: &n_jobs 1
  batch_size: &batch_size 5
  stop_early: &stop_early False
  patience: &patience 11
  epochs: &epochs 40
  verbose: &verbose 0

  mlp_grid: &mlp_grid
    batch_size:
      - 1
      - 5
      - 10
    dropout:
      - 0.0
      - 0.05
      - 0.2
    hidden_layer_sizes:
      - !!python/tuple [5]
      - !!python/tuple [20]
      - !!python/tuple [5,3]
      - !!python/tuple [20,3]
    epochs:
      - 50
      - 100

  kbest_grid: &kbest_grid
    k:
      - 20
      - 50
      - 100

  lgbm_grid: &lgbm_grid
    num_iterations: [10, 30, 50, 80]
    num_leaves: [5, 10, 20, 50]
    min_child_samples: [20, 30, 50]
    min_split_gain: [0.1, 0.01, 0.0]


models:
  knn-finger_ott:
    normalize: "minmax"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      weights: "uniform"

  knn-finger_own:
    normalize: "minmax"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    select:
      variance: True

  knn-finger_relown:
    normalize: "minmax"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      weights: "uniform"

  knn-finger_tugraz:
    normalize: "minmax"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_seqown:
    normalize: "zscore"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    data:
      duration: *duration
      step_duration: *step_duration

  ott_algo-finger_ott:
    normalize: "none"

  mlp-finger_ott:
    normalize: "zscore"
    classifier:
      batch_size: *batch_size
      hidden_layer_sizes: !!python/tuple [5]
      dropout: *dropout
      optimizer: *optimizer
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid: "fingerprint_compare"

  mlp-tsfresh:
    data:
        tsfresh_data: ./data/csv-files/prepared/dataset/train/tsfresh-features_efficient_60seconds_maxlen-100000.data
    normalize: "zscore"
    classifier:
      hidden_layer_sizes: !!python/tuple [5,3]
      dropout: 0.0
      optimizer: *optimizer
      batch_size: 1
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid:
      classifier: *mlp_grid
      selector: *kbest_grid
    select:
      kbest:
        k: 100


  mlp-finger_all:
    normalize: "zscore"
    classifier:
      hidden_layer_sizes: !!python/tuple [15,5]
      dropout: 0.01
      optimizer: *optimizer
      batch_size: *batch_size
      hidden_layer_sizes: !!python/tuple [5]
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid: "fingerprint_compare"

  mlp-finger_own:
    normalize: "zscore"
    classifier:
      hidden_layer_sizes: !!python/tuple [20]
      dropout: 0.0
      optimizer: *optimizer
      batch_size: 1
      epochs: 100
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid: "fingerprint_compare"

  mlp-finger_relown:
    normalize: "zscore"
    classifier:
      hidden_layer_sizes: !!python/tuple [20]
      dropout: 0.0
      optimizer: *optimizer
      batch_size: 1
      epochs: 50
      stop_early: False
      verbose: *verbose
    grid: "fingerprint_compare"

  mlp-finger_tugraz:
    normalize: "zscore"
    classifier:
      batch_size: 1
      hidden_layer_sizes: !!python/tuple [20, 10]
      dropout: 0.05
      optimizer: *optimizer
      epochs: 100
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid: "fingerprint_compare"

  lgbm-finger_ott:
    normalize: "none"
    classifier:
      min_child_samples: 20
      min_split_gain: 0.01
      n_jobs: *n_jobs
      num_iterations: 10
      num_leaves: 5
    grid:
      classifier: *lgbm_grid

  lgbm-finger_tugraz:
    normalize: "none"
    classifier:
      min_child_samples: 50
      min_split_gain: 0.01
      n_jobs: *n_jobs
      num_iterations: 10
      num_leaves: 10
    grid:
      classifier: *lgbm_grid

  lgbm-finger_own:
    normalize: "none"
    classifier:
      min_child_samples: 30
      min_split_gain: 0.0
      n_jobs: *n_jobs
      num_iterations: 80
      num_leaves: 20
    grid:
      classifier: *lgbm_grid

  lgbm-finger_relown:
    normalize: "none"
    classifier:
      class_weight: null
      feature_fraction: 0.8
      max_bin: 127
      min_split_gain: 0.0
      n_jobs: *n_jobs
      num_iterations: 20
      num_leaves: 50
    grid:
      classifier: *lgbm_grid

  lgbm-tsfresh:
    data:
        tsfresh_data: ./data/csv-files/prepared/dataset/train/tsfresh-features_efficient_60seconds_maxlen-100000.data
    normalize: "none"
    classifier:
      n_jobs: *n_jobs
    grid:
      classifier: *lgbm_grid

  lgbm-finger_all:
    normalize: "none"
    classifier:
      class_weight: "balanced"
      feature_fraction: 1.0
      max_bin: 255
      min_child_samples: 50
      min_split_gain: 0.01
      n_jobs: *n_jobs
      num_iterations: 60
      num_leaves: 10
      path_smooth: 0.0
    grid:
      classifier: *lgbm_grid

  svm-finger_ott:
    normalize: "zscore"
    classifier:
      decision_function_shape: "ovr"

  svm-finger_own:
    normalize: "zscore"
    classifier:
      decision_function_shape: "ovr"
      class_weight: "balanced"
    select:
      variance: True

  svm-finger_relown:
    normalize: "zscore"
    classifier:
      class_weight: null
      decision_function_shape: "ovr"
      kernel: "rbf"
    select:
      variance: True

  svm-finger_tugraz:
    normalize: "zscore"
    classifier:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_seqown:
    normalize: "zscore"
    data:
      duration: *duration
      step_duration: *step_duration

  rf-finger_ott:
    normalize: "none"
    classifier:
      class_weight: "balanced"
      bootstrap: True
      min_samples_leaf: 1
      n_jobs: *n_jobs

  rf-finger_own:
    normalize: "none"
    classifier:
      n_jobs: *n_jobs
      class_weight: "balanced"
      bootstrap: True
      min_samples_leaf: 3
    select:
      variance: True

  rf-finger_relown:
    normalize: "none"
    classifier:
      n_jobs: *n_jobs
      class_weight: "balanced"
      bootstrap: False
      min_samples_leaf: 1

  rf-finger_tugraz:
    normalize: "none"
    classifier:
      n_jobs: *n_jobs
      class_weight: "balanced"

  rf-finger_all:
    normalize: "none"
    classifier:
      n_jobs: *n_jobs
      class_weight: "balanced"

  rf-tsfresh:
    data:
        tsfresh_data: ./data/csv-files/prepared/dataset/train/tsfresh-features_efficient_60seconds_maxlen-100000.data
    normalize: "none"
    classifier:
      n_jobs: *n_jobs
    grid: "fingerprint_compare"
