general:
  balance: False
  balance_polarity: False
  calc_cm: True
  calc_train_score: True
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  drop_empty: True
  just_train: False
  max_duration: "60 seconds"
  max_len: null
  min_duration: "5 seconds"
  min_len: 0
  n_jobs: 1
  normalize_pd: True
  output_dir: ./output/tmp_noise
  overwrite_output_dir: False
  repeat: null
  save_models: True
  show_plots: False
  split: True
  step_duration: "30 seconds"
  treat_negative_values: "absolute"
  verbose: True

defects:
- cavity
- floating
- free_particle
- noise
- particle_insulator
- protrusion_earth
- protrusion_hv

models-to-run:
- lgbm-finger_relown

defaults:
  lgbm_grid: &lgbm_grid
    colsample_bytree: [1.0, 0.8]
    min_split_gain: [0.0, 0.01, 0.1, 0.2]
    num_leaves: [5, 10, 20, 30, 50]
    max_bin: [63, 127, 255]

models:
  lgbm-finger_relown:
    normalize: "none"
    classifier:
      class_weight: "balanced"
      colsample_bytree: 0.8
      max_bin: 63
      min_split_gain: 0.1
      n_jobs: 8
      num_leaves: 10
    grid:
      classifier: *lgbm_grid
