general:
  balance: False
  balance_polarity: False
  calc_cm: True
  calc_train_score: False
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  drop_empty: True
  just_train: False
  max_duration: "60 seconds"
  max_len: null
  min_duration: &min_duration "60 seconds"
  min_len: 0
  n_jobs: 1
  normalize_pd: True
  output_dir: ./output/tmp_oned
  overwrite_output_dir: False
  repeat: null
  save_models: True
  show_plots: False
  split: True
  step_duration: "30 seconds"
  treat_negative_values: "absolute"
  verbose: False

defects:
- cavity
- floating
- free_particle
- particle_insulator
- protrusion_earth
- protrusion_hv

models-to-run:
- lgbm-oned_weasel
- knn-sparse
- knn_dtw-oned
- knn_fastdtw-oned
- ridgecv-oned_rocket

defaults:
  n_jobs: &n_jobs 1

models:
  knn-sparse:
    normalize: "none"
    undersample: True
    data:
      fix_duration_str: *min_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      weights: "uniform"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
          - 15
          - 30
        weights:
          - "uniform"
          - "distance"

  knn_fastdtw-oned:
    normalize: "minmax"
    reshaper: True
    undersample: True
    data:
      fix_duration: *min_duration
      frequency: "1ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      weights: "uniform"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 5
          - 15

  knn_dtw-oned:
    normalize: "minmax"
    data:
      fix_duration: *min_duration
      frequency: "40ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 15
      weights: "distance"
      metric: "dtw"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 5
          - 15

  lgbm-oned_weasel:
    normalize: "none"
    data:
      oned:
        fix_duration: *min_duration
        frequency: "100us"
      weasel:
          window_sizes: [1000, 10000, 90000]

  ridgecv-oned_rocket:
    normalize: "none"
    data:
      oned:
        fix_duration: *min_duration
        frequency: "100us"
      rocket:
        num_features: 1000
