general:
  balance: False
  balance_polarity: False
  normalize_pd: True
  calc_train_score: False
  verbose: False
  n_jobs: 1
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/oned_03_23
  overwrite_output_dir: False
  save_models: True
  show_plots: False
  min_duration: &min_duration "60 seconds"
  step_duration: "30 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True
  min_len: 0
  max_len: null
  repeat: null
  treat_negative_values: "absolute"
  cache_dir: ./cache

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - knn_dtw-oned
  - knn-oned_weasel

defaults:
  n_jobs: &n_jobs 1
  verbose: &verbose 0


models:
  knn-oned:
    normalize: "minmax"
    reshaper: True
    data:
      fix_duration: *min_duration
      frequency: "500ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 3
      weights: "distance"
      metric: "euclidean"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
        weights:
          - "uniform"
          - "distance"
        metric:
          - "euclidean"
          - "manhattan"

  knn_dtw-oned:
    normalize: "minmax"
    data:
      fix_duration: *min_duration
      frequency: "50ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 5
      weights: "distance"
      metric: "dtw"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
        weights:
          - "uniform"
          - "distance"
        metric:
          - "dtw"
          - "euclidean"

  pytsknn-oned:
    normalize: "minmax"
    reshaper: True
    data:
      fix_duration: *min_duration
      frequency: "50ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      weights: "distance"
      metric: "dtw_fast"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
        weights:
          - "uniform"
          - "distance"
        metric:
          - "dtw_fast"

  bossvs-oned:
    normalize: "none"
    reshaper: True
    data:
      fix_duration: *min_duration
      frequency: "4ms"
    classifier:
      anova: True
      strategy: "entropy"


  knn-oned_boss:
    normalize: "none"
    data:
      oned:
        fix_duration: *min_duration
        frequency: "2ms"
      boss:
        strategy: "normal"
        anova: True
        window_size: 0.2
        window_step: 0.05
        numerosity_reduction: False
        sparse: False

  knn-oned_weasel:
    normalize: "none"
    data:
      oned:
        fix_duration: *min_duration
        frequency: "200us"
      boss:
        strategy: "entropy"
        numerosity_reduction: False
        sparse: False
