general:
  balance: False
  balance_polarity: False
  normalize_pd: True
  calc_train_score: False
  verbose: False
  n_jobs: 1
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp_oned
  overwrite_output_dir: False
  save_models: True
  show_plots: False
  min_duration: &min_duration "60 seconds"
  step_duration: "30 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True
  min_len: 0
  max_len: null
  repeat: null
  treat_negative_values: "absolute"
  cache_dir: ./cache

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - knn_dtw-oned
  - knn-oned_weasel
  - knn-sparse

defaults:
  n_jobs: &n_jobs 1


models:
  knn-sparse:
    normalize: "none"
    undersample: True
    data:
      fix_duration_str: *min_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      weights: "uniform"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
          - 15
          - 30
        weights:
          - "uniform"
          - "distance"

  knn_dtw-oned:
    normalize: "minmax"
    data:
      fix_duration: *min_duration
      frequency: "40ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 15
      weights: "distance"
      metric: "dtw"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 5
          - 15

  lgbm-oned_weasel:
    normalize: "none"
    data:
      oned:
        fix_duration: *min_duration
        frequency: "100us"
      weasel:
          window_sizes: [1000, 10000, 90000]
