general:
  balance: False
  balance_polarity: False
  normalize_pd: True
  calc_train_score: False
  verbose: True
  n_jobs: 1
  cv: "group"
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp_raw
  overwrite_output_dir: False
  save_models: True
  show_plots: False
  min_duration: null
  step_duration: null
  max_duration: null
  split: False
  drop_empty: True
  min_len: 0
  max_len: null
  repeat: null
  treat_negative_values: "absolute"
  cache_dir: ./cache

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - uknn_dtw-raw
  - polknn_dtw-raw

defaults:
  min_len: &min_len 247
  n_jobs: &n_jobs 1

  knn_grid: &knn_grid
    classifier:
      n_neighbors:
        - 1
        - 3
        - 7
        - 15
        - 30
      weights:
        - "uniform"
        - "distance"
      metric:
        - "dtw"
        - "euclidean"

models:
  uknn_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *min_len
      n_jobs: *n_jobs
      n_neighbors: 4
      metric: "dtw"
      weights: "distance"
    grid: *knn_grid

  usvm_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *min_len
      n_jobs: *n_jobs

  polknn_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *min_len
      n_jobs: *n_jobs
      pos_neighbors: 1
      neg_neighbors: 1
      metric: "dtw"
      weights: "distance"
    grid:
      classifier:
        pos_neighbors:
          - 1
          - 3
          - 7
          - 15
        neg_neighbors:
          - 1
          - 3
          - 7
          - 15
        weights:
          - "uniform"
          - "distance"
        metric:
          - "dtw"
          - "euclidean"
