general:
  balance: False
  balance_polarity: False
  cache_dir: ./cache
  calc_cm: True
  calc_train_score: False
  cv: "group"
  data_dir: ./data/csv-files/prepared/dataset/train
  drop_empty: True
  max_duration: null
  max_len: null
  min_duration: null
  min_len: 0
  n_jobs: 1
  normalize_pd: True
  output_dir: ./output/tmp_raw
  overwrite_output_dir: False
  repeat: null
  save_models: True
  show_plots: False
  split: False
  step_duration: null
  treat_negative_values: "absolute"
  verbose: True

defects:
  - cavity
  - floating
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv

models-to-run:
  - polknn_dtw-raw
  - uknn_dtw-raw

defaults:
  min_len: &min_len 247
  n_jobs: &n_jobs 1

models:
  uknn_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *min_len
      n_jobs: *n_jobs
      n_neighbors: 30
      metric: "dtw"
      weights: "uniform"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
          - 15
          - 30
        weights:
          - "uniform"
          - "distance"

  usvm_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *min_len
      n_jobs: *n_jobs

  polknn_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *min_len
      n_jobs: *n_jobs
      pos_neighbors: 1
      neg_neighbors: 15
      weights: "distance"
    grid:
      classifier:
        pos_neighbors:
          - 1
          - 3
          - 7
          - 15
        neg_neighbors:
          - 1
          - 3
          - 7
          - 15
        weights:
          - "uniform"
          - "distance"
