general:
  cv: 2
  data_dir: ./data/csv-files/testdata_small
  calc_cm: False
  output_dir: ./output/tmp
  overwrite_output_dir: True
  save_models: False
  show_plots: False
  metric: "balanced_accuracy_score"
  min_duration: &min_duration "60 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True
  treat_negative_values: "zero"
  write_cache: False
  # cache_path: /tmp/testdata-cache.p

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - dt-finger_both
  - dt-finger_own
  - dt-finger_tsfresh
  - knn_dtw-oned
  - knn_dtw-twod
  - knn_dtw-seqfinger_both
  - knn_dtw-seqfinger_seqown
  - knn-finger_both
  - knn-finger_own
  - knn-finger_tsfresh
  - mlp-finger_own
  - mlp-finger_tugraz
  - ott_algo-finger_ott
  - svm_dtw-seqfinger_ott
  - svm_dtw-seqfinger_seqown
  - svm-finger_both
  - svm-finger_tsfresh

defaults:
  duration: &duration "30 seconds"
  step_duration: &step_duration "10 seconds"
  tsfresh_data: &tsfresh_data ./data/csv-files/testdata_small/tsfresh-features-0.6.1_minimal_60seconds.data
  normalize: &normalize True
  n_jobs: &n_jobs 1
  stop_early: &stop_early True
  patience: &patience 1
  epochs: &epochs 10
  verbose: &verbose 1

models:
  knn_dtw-oned:
    normalize: *normalize
    data:
      fix_duration: *min_duration
      frequency: "5000ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-twod:
    data:
      max_len: 100000
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_ott:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_own:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_tugraz:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_both:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_tsfresh:
    default_fc_parameters: MinimalFCParameters
    n_jobs: *n_jobs
    normalize: *normalize
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier:
      n_neighbors: 1

  knn_dtw-seqfinger_ott:
    normalize: False
    data:
      duration: *duration
      step_duration: *step_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_seqown:
    normalize: False
    data:
      duration: *duration
      step_duration: *step_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_tugraz:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_both:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  ott_algo-finger_ott:
    normalize: False

  mlp-finger_ott:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      batch_size: 6
      hidden_layer_sizes:
        - 4
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  mlp-finger_own:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      hidden_layer_sizes:
        - 3
      dropout: 0.05
      optimizer: "adam"
      batch_size: 6
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  mlp-finger_tugraz:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      batch_size: 6
      hidden_layer_sizes:
        - 4
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  mlp-finger_both:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      batch_size: 6
      hidden_layer_sizes:
        - 6
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  svm-finger_ott:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_own:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_tugraz:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_both:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_tsfresh:
    normalize: *normalize
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_both:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  svm_dtw-seqfinger_ott:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  svm_dtw-seqfinger_seqown:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  svm_dtw-seqfinger_tugraz:
    duration: *duration
    normalize: *normalize
    step_duration: *step_duration

  dt-finger_ott:
    normalize: False

  dt-finger_own:
    normalize: False

  dt-finger_tugraz:
    normalize: False

  dt-finger_both:
    normalize: False

  dt-finger_tsfresh:
    normalize: False
    n_jobs: *n_jobs
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
