general:
  cv: 2
  data_dir: ./data/csv-files/testdata_small
  calc_cm: False
  output_dir: ./output/tmp
  overwrite_output_dir: True
  save_models: False
  show_plots: False
  metric: "balanced_accuracy_score"
  min_duration: "60 seconds"
  max_duration: "60 seconds"
  split: True

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - dt-finger_both
  - dt-finger_own
  - dt-finger_tsfresh
  - knn_dtw-oned
  - knn_dtw-twod
  - knn_dtw-seqfinger_both
  - knn_dtw-seqfinger_own
  - knn-finger_both
  - knn-finger_own
  - knn-finger_tsfresh
  - mlp-finger_own
  - mlp-finger_tugraz
  - ott_algo-finger_ott
  - svm_dtw-seqfinger_ott
  - svm_dtw-seqfinger_own
  - svm-finger_both
  - svm-finger_tsfresh

defaults:
  step_duration: &step_duration "10 seconds"
  tsfresh_data: &tsfresh_data ./data/csv-files/testdata_small/tsfresh-features_0.5.0_minimal_60seconds.data

models:
  knn_dtw-oned:
    frequency: "5000ms"
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-twod:
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_ott:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_own:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_both:
    normalize: True
    classifier_hyperparameters:
      n_neighbors: 1

  knn-finger_tsfresh:
    normalize: True
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_ott:
    duration: "30 seconds"
    normalize: False
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_own:
    duration: "30 seconds"
    normalize: False
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_tugraz:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_both:
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration
    classifier_hyperparameters:
      n_neighbors: 1

  knn_dtw-seqfinger_tsfresh:
    n_jobs: 3
    fdr_level: 0.23
    duration: "30 seconds"
    normalize: True
    step_duration: *step_duration
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      n_neighbors: 1

  ott_algo-finger_ott:
    normalize: True

  mlp-finger_ott:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_own:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 3
      optimizer: "adam"
      max_iter: 300
      max_fun:  20000
      epochs: 123


  mlp-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 4
      optimizer: "adam"
      epochs: 123

  mlp-finger_both:
    normalize: True
    classifier_hyperparameters:
      batch_size: 6
      hidden_layer_sizes:
        - 6
      optimizer: "adam"
      epochs: 123

  mlp-finger_tsfresh:
    normalize: True
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      batch_size: 5
      hidden_layer_sizes:
        - 9
      optimizer: "adam"
      epochs: 123

  svm-finger_ott:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_own:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tugraz:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_both:
    normalize: True
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm-finger_tsfresh:
    normalize: True
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
    classifier_hyperparameters:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_both:
    duration: "30 seconds"
    step_duration: *step_duration
    normalize: True

  svm_dtw-seqfinger_ott:
    duration: "30 seconds"
    step_duration: *step_duration
    normalize: True

  svm_dtw-seqfinger_own:
    duration: "30 seconds"
    step_duration: *step_duration
    normalize: True

  svm_dtw-seqfinger_tugraz:
    duration: "30 seconds"
    step_duration: *step_duration
    normalize: True

  dt-finger_ott:
    normalize: True

  dt-finger_own:
    normalize: True

  dt-finger_tugraz:
    normalize: True

  dt-finger_both:
    normalize: True

  dt-finger_tsfresh:
    normalize: True
    n_jobs: 3
    fdr_level: 0.23
    tsfresh_data: *tsfresh_data
