general:
  calc_train_score: True
  verbose: False
  n_jobs: 3
  cv: 2
  data_dir: ./data/csv-files/testdata_small
  calc_cm: False
  output_dir: ./output/tmp
  overwrite_output_dir: True
  save_models: False
  show_plots: False
  min_duration: &min_duration "60 seconds"
  max_duration: "60 seconds"
  split: True
  drop_empty: True
  treat_negative_values: "absolute"
  use_cache: True
  cache_dir: ./cache

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - dt-finger_tugraz
  - dt-finger_own
  - knn_dtw-oned
  - knn_dtw-twod
  - knn_dtw-seqfinger_seqown
  - knn-finger_ott
  - knn-finger_own
  - mlp-finger_all
  - mlp-finger_own
  - mlp-finger_tugraz
  - ott_algo-finger_ott
  - rf-finger_tugraz
  - svm_dtw-seqfinger_seqown
  - svm-finger_ott

defaults:
  duration: &duration "30 seconds"
  step_duration: &step_duration "10 seconds"
  normalize: &normalize True
  n_jobs: &n_jobs 1
  stop_early: &stop_early False
  patience: &patience 1
  epochs: &epochs 10
  verbose: &verbose 0

  dt_grid: &dt_grid
    min_samples_split:
      - 2
      - 5
      - 10
      - 20
    class_weight:
      - "balanced"
      - null
    max_features:
      - null
      - 5
    min_samples_leaf:
      - 1
      - 3
      - 5
      - 10

  mlp_grid: &mlp_grid
    callbacks:
      - null
    hidden_layer_sizes:
      - !!python/tuple [3]
      - !!python/tuple [3, 3]
    dropout:
      - 0.01
      - 0.05
    epochs:
      - 10
      - 20

models:
  knn_dtw-oned:
    normalize: *normalize
    data:
      fix_duration: *min_duration
      frequency: "5000ms"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-twod:
    data:
      max_len: 100000
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_ott:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn-finger_own:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    select:
      variance: True

  knn-finger_tugraz:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
    grid:
      classifier: *dt_grid

  knn-finger_both:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  knn_dtw-seqfinger_seqown:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1

  ott_algo-finger_ott:
    normalize: False

  mlp-finger_ott:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      batch_size: 6
      hidden_layer_sizes:
        - 4
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid:
      classifier: *mlp_grid

  mlp-finger_own:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      hidden_layer_sizes: !!python/tuple [3]
      dropout: 0.05
      optimizer: "adam"
      batch_size: 6
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid:
      classifier: *mlp_grid
    select:
      variance: True
      rfe:
        features: 20

  mlp-finger_all:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      hidden_layer_sizes: !!python/tuple [3]
      dropout: 0.05
      optimizer: "adam"
      batch_size: 6
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose
    grid:
      classifier: *mlp_grid
    select:
      variance: True


  mlp-finger_tugraz:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      batch_size: 6
      hidden_layer_sizes:
        - 4
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  mlp-finger_both:
    normalize: *normalize
    classifier:
      n_jobs: *n_jobs
      batch_size: 6
      hidden_layer_sizes:
        - 6
      dropout: 0.05
      optimizer: "adam"
      epochs: *epochs
      stop_early: *stop_early
      patience: *patience
      verbose: *verbose

  svm-finger_ott:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_own:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"
    select:
      variance: True

  svm-finger_tugraz:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm-finger_both:
    normalize: *normalize
    classifier:
      decision_function_shape: "ovr"

  svm_dtw-seqfinger_seqown:
    normalize: *normalize
    data:
      duration: *duration
      step_duration: *step_duration

  dt-finger_ott:
    normalize: *normalize
    grid:
      classifier: *dt_grid

  dt-finger_own:
    normalize: *normalize
    grid:
      classifier: *dt_grid
    select:
      variance: True

  dt-finger_tugraz:
    normalize: *normalize
    grid:
      classifier: *dt_grid

  dt-finger_both:
    normalize: *normalize

  rf-finger_ott:
    normalize: *normalize

  rf-finger_own:
    normalize: *normalize
    select:
      variance: True

  rf-finger_tugraz:
    normalize: *normalize
