general:
  balance: False
  balance_polarity: False
  normalize_pd: True
  calc_train_score: False
  verbose: False
  n_jobs: 1
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  calc_cm: True
  output_dir: ./output/tmp_twod
  overwrite_output_dir: True
  save_models: True
  show_plots: False
  min_duration: null
  step_duration: null
  max_duration: null
  split: True
  drop_empty: True
  min_len: 0
  max_len: &max_len 247
  repeat: 16
  treat_negative_values: "absolute"
  cache_dir: ./cache

defects:
  - free_particle
  - particle_insulator
  - protrusion_earth
  - protrusion_hv
  - floating
  - cavity

models-to-run:
  - knn_dtw-twod

defaults:
  n_jobs: &n_jobs 6
  verbose: &verbose 0

  knn_grid: &knn_grid
    classifier:
      n_neighbors:
        - 1
        - 3
        - 7
        - 15
        - 30
      weights:
        - "uniform"
        - "distance"
      metric:
        - "dtw"
        - "euclidean"

models:
  knn_dtw-twod:
    normalize: "none"
    data:
      max_len: *max_len
      normalize: "none"
    classifier:
      n_jobs: *n_jobs
      n_neighbors: 1
      metric: "dtw"
    grid: *knn_grid

  uknn_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *max_len
      n_jobs: *n_jobs
      n_neighbors: 4
      metric: "dtw"
      weights: "distance"
    grid: *knn_grid

  polknn_dtw-raw:
    normalize: "none"
    classifier:
      min_len: *max_len
      n_jobs: *n_jobs
      pos_neighbors: 1
      neg_neighbors: 1
      metric: "dtw"
      weights: "distance"
    grid:
      classifier:
        pos_neighbors:
          - 1
          - 3
          - 7
          - 15
        neg_neighbors:
          - 1
          - 3
          - 7
          - 15
        weights:
          - "uniform"
          - "distance"
        metric:
          - "dtw"
          - "euclidean"
