general:
  balance: False
  balance_polarity: False
  cache_dir: ./cache
  calc_cm: True
  calc_train_score: False
  cv: "group"
  data_dir: ./data/csv-files/prepared/dataset/train
  drop_empty: False
  just_train: False
  max_duration: null
  max_len: &max_len 247
  min_duration: null
  min_len: 0
  n_jobs: 4
  normalize_pd: False
  output_dir: ./output/tune-raw-knn-dtw
  overwrite_output_dir: False
  repeat: 13
  save_models: True
  show_plots: False
  split: True
  step_duration: null
  treat_negative_values: "absolute"
  verbose: False

defects:
- free_particle
- particle_insulator
- protrusion_earth
- protrusion_hv
- floating
- cavity

models-to-run:
- knn_dtw-twod

models:
  knn_dtw-twod:
    normalize: "none"
    data:
      normalize: "minmax"
      append_prepend_0: False
    classifier:
      n_jobs: 2
      n_neighbors: 7
      weights: "distance"
      metric: "dtw"
      metric_params:
        sakoe_chiba_radius: 4
    grid:
      data:
        normalize:
          - "minmax"
          - "zscore"
        append_prepend_0:
          - True
          - False
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
        weights:
          - "uniform"
          - "distance"
        metric_params:
          - {sakoe_chiba_radius: 4}
          - {sakoe_chiba_radius: 8}
          - {sakoe_chiba_radius: 16}
          - {sakoe_chiba_radius: 32}
          - {sakoe_chiba_radius: 64}
