general:
  balance: False
  balance_polarity: False
  cache_dir: ./cache
  calc_cm: True
  calc_train_score: False
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  drop_empty: True
  just_train: False
  max_duration: null
  max_len: &max_len 247
  min_duration: null
  min_len: 0
  n_jobs: 1
  normalize_pd: True
  output_dir: ./output/tmp_twod
  overwrite_output_dir: False
  repeat: 16
  save_models: True
  show_plots: False
  split: True
  step_duration: null
  treat_negative_values: "absolute"
  verbose: False

defects:
- free_particle
- particle_insulator
- protrusion_earth
- protrusion_hv
- floating
- cavity

models-to-run:
- knn_dtw-twod

models:
  knn_dtw-twod:
    normalize: "none"
    data:
      max_len: *max_len
      normalize: "none"
    classifier:
      n_jobs: 6
      n_neighbors: 1
      metric: "dtw"
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
          - 15
          - 30
        weights:
          - "uniform"
          - "distance"
        metric:
          - "dtw"
          - "euclidean"
