general:
  balance: True
  balance_polarity: True
  cache_dir: ./cache
  calc_cm: True
  calc_train_score: False
  cv: "logo"
  data_dir: ./data/csv-files/prepared/dataset/train
  drop_empty: False
  just_train: False
  max_duration: null
  max_len: &max_len 247
  min_duration: null
  min_len: 0
  n_jobs: 4
  normalize_pd: True
  output_dir: ./output/tune-raw-knn-dtw-window-size
  overwrite_output_dir: False
  repeat: 12
  save_models: True
  show_plots: False
  split: True
  step_duration: null
  treat_negative_values: "absolute"
  verbose: True

defects:
- free_particle
- particle_insulator
- protrusion_earth
- protrusion_hv
- floating
- cavity

models-to-run:
- knn_dtw-twod

models:
  knn_dtw-twod:
    normalize: "none"
    data:
      normalize: "none"
    classifier:
      n_jobs: 2
      n_neighbors: 3
      weights: "uniform"
      metric: "dtw"
      metric_params:
        sakoe_chiba_radius: 64
    grid:
      classifier:
        n_neighbors:
          - 1
          - 3
          - 7
          - 15
        weights:
          - "uniform"
          - "distance"
        metric_params:
          - {sakoe_chiba_radius: 1}
          - {sakoe_chiba_radius: 2}
          - {sakoe_chiba_radius: 4}
          - {sakoe_chiba_radius: 8}
          - {sakoe_chiba_radius: 16}
          - {sakoe_chiba_radius: 32}
          - {sakoe_chiba_radius: 64}
          - {sakoe_chiba_radius: 128}
