name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install pip==21.2.3
    - run: pip install nox==2020.12.31
    - run: pip install poetry==1.1.7
    - run: pip install nox-poetry==0.8.6
    - run: nox
    - run: poetry build
    - name: upload package to Gitlab pypi
      env:
        POETRY_HTTP_BASIC_TUBERLINGITLAB_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_TUBERLINGITLAB_USERNAME }}
        POETRY_HTTP_BASIC_TUBERLINGITLAB_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_TUBERLINGITLAB_PASSWORD }}
      run: poetry publish -r tuberlingitlab
