name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install pip==21.0.1
    - run: pip install nox==2020.12.31
    - run: pip install poetry==1.1.6
    - run: pip install nox-poetry==0.8.4
    - run: nox --no-venv
