name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: python -m pip install pip==21.2.4
    - run: python -m pip install nox==2022.11.21
    - run: python -m pip install poetry==1.1.15
    - run: python -m pip install nox-poetry==1.0.2
    - run: nox
