name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  tests:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: python -m pip install pip==21.2.4
    - run: python -m pip install nox==2020.12.31
    - run: python -m pip install poetry==1.1.11
    - run: python -m pip install nox-poetry==0.8.6
    - run: nox
